### ISSUE TITLE
上传分数时使用蜂窝移动网络无法正常提交

### ISSUE THREAD

**Issue by TheSorry404** [Louiswu2011/chafenqi#33]
如题，直接在Wi-Fi环境下点击链接可以正常显示
![BF298F8D-DB10-4EA2-83A0-3ABF1C6D0258](https://user-images.githubusercontent.com/39026959/226168385-e957b97a-d6fe-42eb-a90d-ff72317dc0e2.png)，开启代理后可以正常上传分数
![C8A6242C-1589-4F19-B9D3-497CC1AE4069](https://user-images.githubusercontent.com/39026959/226168450-1f6045fe-e4ce-4c34-a910-620b130413d0.png)
但切换5G后再开启代理上传会提示网络错误或无法操作下一步
![241E0C03-5B43-4E8C-877F-19507BC60EDB](https://user-images.githubusercontent.com/39026959/226168533-257df435-a044-4d19-863d-15ba52aa8c94.png)
问题目前看来我这边可以复现，不清楚是否可能与DNS解析或相关流程有关
网络环境：蜂窝网络 长春联通5G  Wi-Fi网络 长春电信  设备iPhone 12 Pro  系统版本 16.3

**Comment by Louiswu2011** [comment]
感谢反馈！

这个类似的问题我有时候自己用的时候也会遇到，具体表现就是一直卡在加载没有确认访问。目前我这边猜想的微信打开网页流程是这样的：
- 点击网页链接之后先跳转到微信的域名（这点可以将网页添加到悬浮还是啥的确认）
- 显示确认访问的页面
- 用户确认后再跳转到目标域名

之前在测试的时候，已经在代理服务器端放行了基本上会跳转的微信域名，但还是时不时的抽风，也就是卡在加载不出来微信域名的阶段，暂时不知道解决的方法，貌似和网络环境有一定的关系，得慢慢研究一下。
