### ISSUE TITLE
最近记录没有同步并且出现闪退情况

### ISSUE THREAD

**Issue by Tong11180** [Louiswu2011/chafenqi#36]
rt，此为最近三首游玩记录
![8C97DB58-747E-4593-AA7C-1EE3008C8A70](https://user-images.githubusercontent.com/128557691/226774714-8f0ddce3-c661-4f44-a3e0-fff7d08f41fc.png)
更新后在app的显示为
![AB01073F-C70C-4D9D-BCE6-AFAE759EBA62](https://user-images.githubusercontent.com/128557691/226774779-bdd42b2e-1eaa-4463-a369-056e39e580de.png)
点击显示全部会出现闪退情况

**Comment by Louiswu2011** [comment]
感谢反馈！

首先，最近动态这里显示的三首分别是最近游玩的一首、最近的新纪录和最近的高分记录，并不是近三首游玩的歌曲；点击显示全部闪退的话，如果你是从老版本直接升级上来的话，请尝试重装App看看能不能解决，还是不能的话请提供一下你的查分器账号名，我在后台查一下有没有记录。
